# Generated by Django 2.1.4 on 2019-09-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0003_auto_20190924_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-01-01')),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.CharField(max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnival.Carnival')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnival.Grade')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.Rider')),
            ],
        ),
    ]
