# Generated by Django 2.1.4 on 2019-09-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='title',
        ),
    ]
