# Generated by Django 2.1.4 on 2019-09-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0002_auto_20190925_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='grade',
            new_name='race',
        ),
    ]
