# Generated by Django 2.1.4 on 2019-09-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0003_auto_20190925_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnival',
            name='categories',
            field=models.ManyToManyField(to='carnival.Grade'),
        ),
    ]
