# Generated by Django 2.1.4 on 2019-10-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0006_result_bib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fouth'), (5, 'Fifth'), (6, 'Sixth'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (901, 'First unplaced woman'), (910, 'Unplaced'), (920, 'DNF'), (990, 'DNS'), (999, 'Disqualified')], default=910, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Racetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.CharField(choices=[('crit', 'Criterium'), ('road', 'Road Race'), ('itt', 'Individual Time Trial'), ('ttt', 'Team Time Trial'), ('hand', 'Handicap')], default='crit', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='event',
        ),
        migrations.RemoveField(
            model_name='result',
            name='race',
        ),
        migrations.RemoveField(
            model_name='result',
            name='rider',
        ),
        migrations.AddField(
            model_name='register',
            name='finish_time',
            field=models.TimeField(default='0:00:00'),
        ),
        migrations.AddField(
            model_name='register',
            name='prime_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='prime_three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='prime_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='start_time',
            field=models.TimeField(default='0:00:00'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='register',
            name='result',
            field=models.ForeignKey(default=910, on_delete=django.db.models.deletion.CASCADE, to='carnival.Place'),
        ),
    ]
