# Generated by Django 2.1.4 on 2019-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0007_auto_20191012_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fouth', 'Fouth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('First unplaced woman', 'First unplaced woman'), ('Unplaced', 'Unplaced'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('Disqualified', 'Disqualified')], default='Unplaced', max_length=4),
        ),
    ]
