# Generated by Django 2.1.4 on 2019-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0008_auto_20191012_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('1UW', '1UW'), ('Unp', 'Unp'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DQ', 'DQ')], default='Unp', max_length=4),
        ),
        migrations.AlterField(
            model_name='racetype',
            name='race_type',
            field=models.CharField(choices=[('crit', 'Criterium'), ('road', 'Road Race'), ('itt', 'ITT'), ('ttt', 'TTT'), ('hand', 'Handicap')], default='crit', max_length=9),
        ),
    ]
