# Generated by Django 2.1.4 on 2019-10-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0009_auto_20191012_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('FUW', 'FUW'), ('UNP', 'UNP'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DQ', 'DQ')], default='UNP', max_length=4),
        ),
        migrations.AlterField(
            model_name='register',
            name='result',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carnival.Place'),
        ),
    ]
