# Generated by Django 2.1.4 on 2019-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnival', '0010_auto_20191013_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='prime_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='prime_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='prime_two',
            field=models.BooleanField(default=False),
        ),
    ]
